### ISSUE TITLE
TODO(2019/2/7)

### ISSUE THREAD

**Issue by ThorTaro** [ThorTaro/NodeAndEdgeView#6]
## TODO
- [ ] EdgeViewを操作する機能の追加
  - [ ] EdgeView用のSideMenuの用意(ボタンは削除のみ)
  - [ ] EdgeViewをLongPressできるようにする
  - [ ] EdgeViewとEdgeModelやEdgeMapModelも同期させる

- [ ] AncestorViewを操作する機能の改善
  - [ ] Ancestor用のSideMenuの用意(ボタンはText EditとCreate Edgeのみ)

- [ ] AncestorViewとDescendantViewの見た目を自由に変更できようにする
  - [ ] 透明なUIViewの上にCALayerとかを置くように変更する
  - [ ] AncestorViewはいい感じの楕円に，DescendantViewはとりあえず今のままの形をCALayerで記述する

- [ ] 全体的にイイカンジに配色とか形とか直す
  - [ ] ShadowとかBorderColorとかいじってそれっぽくする

**Comment by ThorTaro** [comment]
## TODO
- [x] EdgeViewを操作する機能の追加
  - [x] ~~EdgeView用のSideMenuの用意(ボタンは削除のみ)~~
  SideMenuではなく出たり消えたりする削除ボタンを追加することで済ませた
  - [x] ~~EdgeViewをLongPressできるようにする~~
  SIdeMenuがなくなったためLongPressさせる必要がなくなったので削除
  - [x] EdgeViewとEdgeModelやEdgeMapModelも同期させる

- [ ] AncestorViewを操作する機能の改善
  - [ ] Ancestor用のSideMenuの用意(ボタンはText EditとCreate Edgeのみ)

- [ ] AncestorViewとDescendantViewの見た目を自由に変更できようにする
  - [ ] 透明なUIViewの上にCALayerとかを置くように変更する
  - [ ] AncestorViewはいい感じの楕円に，DescendantViewはとりあえず今のままの形をCALayerで記述する

- [ ] 全体的にイイカンジに配色とか形とか直す
  - [ ] ShadowとかBorderColorとかいじってそれっぽくする
  - [ ] Animationをイイカンジに使ってそれっぽく表示できるようにする

**Comment by ThorTaro** [comment]
AncestorView専用のSideMenuを用意する予定だったけど，なんかうまくいったので用意せずに済んだ．

**Comment by ThorTaro** [comment]
## TODO
- [x] EdgeViewを操作する機能の追加
  - [x] ~~EdgeView用のSideMenuの用意(ボタンは削除のみ)~~
  SideMenuではなく出たり消えたりする削除ボタンを追加することで済ませた
  - [x] ~~EdgeViewをLongPressできるようにする~~
  SIdeMenuがなくなったためLongPressさせる必要がなくなったので削除
  - [x] EdgeViewとEdgeModelやEdgeMapModelも同期させる

- [x] AncestorViewを操作する機能の改善
  - [x] Ancestor用のSideMenuの用意(ボタンはText EditとCreate Edgeのみ)

- [x] AncestorViewとDescendantViewの見た目を自由に変更できようにする
  - [x] 透明なUIViewの上にCALayerとかを置くように変更する
  - [x] AncestorViewはいい感じの楕円に，DescendantViewはとりあえず今のままの形をCALayerで記述する

- [ ] 全体的にイイカンジに配色とか形とか直す
  - [ ] ShadowとかBorderColorとかいじってそれっぽくする
  - [ ] Animationをイイカンジに使ってそれっぽく表示できるようにする

**Comment by ThorTaro** [comment]
見た目をイイカンジに直す前に中身をイイカンジに直したほうがいいと思う

**Comment by ThorTaro** [comment]
バグ発見した
EdgeViewが真横の時(多分真縦もだと思う)に削除ボタンが動作しない
これは真横とか真縦の時に下のUIViewが四角形から完全な直線になっちゃっていて，ボタンのサイズに関係なくUIViewの外側なので反応しないのが原因
でも，これってよく考えてみると真横や真縦以外でも下のUIViewが細くなってたら効かなくなるんじゃ．．．

**Comment by ThorTaro** [comment]
解決策を考えついたので，ブランチ先のファイルにメモを残しておいた
大掛かりな改変は多分しないで済む

**Comment by ThorTaro** [comment]
MenuViewに使っているTableViewのボタンの入れ替え時の描画が超面倒なことになっている
TableViewにした理由も特にないので単純なUIButtonに変更しようと思う
最近AutoLayoutも勉強しているんだけど，ライフサイクルの関係で結構面倒なことになっている
ひとまず今回のプロジェクトではAutoLayoutを使うのは諦めてやっていく感じの方がうまくいきそう

**Comment by ThorTaro** [comment]
大型リファクタリング兼関数の中身の見直し兼疎結合にできないかを見直したところ
Menu系に関しては，そもそも完成していないので，まだリファクタリングに着工できずにいる

**Comment by ThorTaro** [comment]
だいぶ時間が空いたけど，現状納得のいくリファクタリングと，簡単なロジックの見直しをした
MenuView周りはリファクタリングに加えて，Relationshipも操作できるようにした
ひとまずリファクタリングも終わったので，TODOに戻ろうと思う

**Comment by ThorTaro** [comment]
イイ感じに見た目をいじったので，フロントエンドは終了かな．

**Comment by ThorTaro** [comment]
次はバックエンド(多分)
